//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by K:\RR\RR\rrw32\rrw.RC
//
#define BTN_UNCHECKED                   0
#define BTN_CHECKED                     1
#define IDD_PREFDIS                     1
#define BTN_UNKNOWN                     2
#define DIFIELD                         3
#define IDC_PB_REPLACE_ALL              3
#define IDOK2                           3
#define IDOK1                           3
#define IDC_PB_FIND_NEXT                5
#define IDC_RB0                         60
#define IDC_RB1                         61
#define IDC_RB2                         62
#define IDC_RB3                         63
#define IDC_RB4                         64
#define IDC_RB5                         65
#define IDC_RB6                         66
#define IDC_RB7                         67
#define IDC_RB8                         68
#define IDC_RB9                         69
#define IDC_RB10                        70
#define IDC_RB11                        71
#define IDC_RB12                        72
#define IDC_RB13                        73
#define IDC_RB14                        74
#define IDC_RB15                        75
#define IDC_RB16                        76
#define IDC_RB17                        77
#define IDC_RB18                        78
#define IDC_RB19                        79
#define IDB_ABRABUT                     100
#define IDB_CUSTOM                      100
#define IDD_FILE_PROPERTIES             132
#define IDD_DEFAULT_FILE_SETTINGS       134
#define DGPPARAM                        202
#define DTRIMNO2                        204
#define DTRIMYES2                       205
#define IDC_EXPORTOLE2                  206
#define DEDCOPY                         207
#define DLBSTYLE1                       209
#define DIMAGEGET2                      212
#define DL_NEW_PAGE                     213
#define IDC_CHECK_NPL                   213
#define IDC_PB_FIELD                    213
#define DLEFTFIELD                      214
#define IDC_CHECK_NORF                  214
#define IDC_CHECK_NRF                   214
#define DRIGHTFIELD                     215
#define DEDADD                          301
#define DIALOGJOINHELP                  301
#define DLIBCLOSE                       1001
#define IDC_CHECK_BROWSE                1007
#define IDC_EDIT1                       1015
#define IDC_MAXEDIT                     1015
#define DPARAMFIELDNAME                 1015
#define DDEFAULTVALUE                   1015
#define DPPRESENTVALUE                  1015
#define IDC_SUBJECT                     1015
#define TEXTHELLO                       1015
#define DLITERALEND                     1015
#define DTOLITERAL                      1015
#define IDC_AUTOSAVEMIN                 1015
#define IDC_EB_CHARACTER                1015
#define IDC_EB_DPASS                    1015
#define IDC_EB_EXP                      1015
#define IDC_EB_CONDITION                1015
#define IDC_EB_TARGET                   1015
#define IDC_EB_LINE                     1015
#define IDC_EB_SUBJECT_FIELD            1015
#define IDC_EB_DEFAULT                  1015
#define IDC_EB_VALIDATION               1015
#define IDC_EB_VALUE                    1015
#define IDC_EB_FIELD                    1015
#define IDC_EB_LOPARAM                  1015
#define IDC_EB_FROM                     1015
#define IDC_EB_FROM_FIELD               1015
#define IDC_EB_TARGET_FIELD             1015
#define IDC_FILESETTINGS_LOOKUP         1015
#define IDC_FILESETTINGS_LOOKUP_DIRECTORY 1015
#define IDC_EB_COMMENT                  1016
#define IDC_EXPORT_OLE                  1016
#define DFROMLITERAL                    1016
#define IDC_EB_RPASS                    1016
#define IDC_EB_NAME2                    1016
#define IDC_EDIT2                       1016
#define IDC_EDIT                        1016
#define IDC_EB_BAND                     1016
#define IDC_EB_MESSAGE_FIELD            1016
#define IDC_EB_DESCRIPTION              1016
#define IDC_EB_HIPARAM                  1016
#define IDC_EB_TO                       1016
#define IDC_EB_TO_FIELD                 1016
#define DINDFILE03                      1016
#define IDC_OpenInBrowser               1017
#define IDC_EDIT3                       1017
#define IDC_EB_TOTAL                    1017
#define IDC_EB_LOGICAL                  1017
#define IDC_EB_SENDTO_FIELD             1017
#define IDC_EB_TABLE                    1017
#define DRELKEYEXP_FLEXLINK             1017
#define IDC_BUTTON_CREATE_HTML          1018
#define IDC_EDIT4                       1018
#define IDC_EB_VALUE_FIELD              1018
#define IDC_BUTTON_PDI_EXPORT           1019
#define IDC_EDIT5                       1019
#define IDC_EB_DYN_TABLE                1019
#define IDC_EDIT6                       1020
#define IDC_CASECHECK                   1021
#define IDC_EDIT7                       1021
#define IDC_VALUEEDIT1                  1022
#define IDC_BUTTON_FILEBROWSE           1022
#define IDC_EDIT8                       1022
#define IDC_VALUELIST                   1023
#define IDC_IGNORE_MARGINS              1023
#define IDC_ADDBUTTON                   1024
#define IDC_DELETEBUTTON                1025
#define DBFS                            1025
#define IDC_FETCHBUTTON                 1026
#define DEDEXPR1                        1026
#define IDC_COLLIST                     1027
#define DPREFBANDCLR1                   1027
#define IDC_BUTTON1                     1027
#define DEDITKEY                        1027
#define DPARAMMOVEUP                    1027
#define DEDITFORMAT                     1027
#define DPACCEPT                        1027
#define SSFIELD                         1027
#define DLISTADD                        1027
#define ID_BROWSE                       1027
#define IDC_FILEBROWSE                  1027
#define IDC_PB_NAME                     1027
#define IDC_PB1                         1027
#define IDC_PB_CONDITION                1027
#define IDC_PB_SELECT                   1027
#define IDC_PB_SUBJECT                  1027
#define IDC_PB_MOVEUP                   1027
#define IDC_PB_SELECT_FIELD             1027
#define IDC_PB_LOPARAM                  1027
#define IDC_PB_FROM                     1027
#define IDC_PB_DATE                     1027
#define IDC_PB_FROM_FIELD               1027
#define IDC_PB_DATE_ENTRY               1027
#define IDC_FILESETTINGS_LOOKUP_BROWSE  1027
#define IDDICT                          1027
#define IDC_SELTEXT                     1028
#define IDC_MAPI_OPTIONS                1028
#define DMAKECALC                       1028
#define DLISTEDIT                       1028
#define IDC_PB_FILE                     1028
#define IDC_PB_NAME2                    1028
#define IDC_PB2                         1028
#define IDC_PB_REMOVE                   1028
#define IDC_PB_DELETE                   1028
#define IDC_PB_CALC                     1028
#define IDC_PB_MESSAGE                  1028
#define IDC_PB_HIPARAM                  1028
#define IDC_PB_TO                       1028
#define IDC_PB_TO_FIELD                 1028
#define IDC_UNIQUETEXT                  1029
#define DLISTDELETE                     1029
#define IDC_PB_ORIGIN                   1029
#define IDC_PB3                         1029
#define IDC_PB_SENDTO                   1029
#define IDC_PB_DEFAULT                  1029
#define IDC_UNIQUECOUNT                 1030
#define IDC_SEND_ENTIRE                 1030
#define DPARAMMOVEDOWN                  1030
#define IDC_PB_TYPE                     1030
#define IDC_PB4                         1030
#define IDC_PB_MOVEDOWN                 1030
#define IDC_MAXTEXT                     1031
#define IDC_SEND_BURST                  1031
#define IDC_PB_TYPE2                    1031
#define IDC_PB5                         1031
#define IDC_AUTO_SEND                   1032
#define DDEFAULT                        1032
#define IDC_PB6                         1032
#define IDC_CLEARBUTTON                 1033
#define IDC_SENDTO_COMBO                1033
#define DPARAMNEW                       1033
#define IDC_PB7                         1033
#define IDC_PB_NEW                      1033
#define IDC_BURST_LEVEL                 1034
#define IDC_MODIFYBUTTON                1034
#define DPARAMEDIT                      1034
#define IDC_PB8                         1034
#define IDC_PB_OK                       1034
#define DPARAMDELETE                    1035
#define IDC_SENDTO_EDIT                 1035
#define IDC_PB_CANCEL                   1035
#define IDC_STATIC_BURSTLEVEL           1036
#define DPARAMCOMMENT                   1036
#define IDC_PB_COMMENT                  1036
#define DPARAMDEFAULT                   1037
#define IDC_STATIC_SENDTO_EDIT          1037
#define DPARAMCOPY                      1037
#define IDC_PB_COPY                     1037
#define IDC_MESSAGE                     1039
#define IDC_STATIC_MESSAGE              1040
#define DVALIDATION                     1040
#define DEDITVALIDATION                 1041
#define DPROMPTSTRING                   1042
#define DINSTRUCTIONSTRING              1042
#define DERRORSTRING                    1043
#define DPARAMFIELDS                    1044
#define DDELETEVALIDATION               1044
#define DFORMAT                         1045
#define DCHECKPROMPT                    1047
#define DCHECKREPLACE                   1048
#define DPCOMMENT                       1055
#define DPARAMVALUES                    1056
#define DPNEWVALUE                      1057
#define DPACCEPTON                      1058
#define DPACCEPTOFF                     1059
#define DFWIDTH                         1060
#define DFWSPIN                         1061
#define DPREVERT                        1062
#define DPROMPTNAME                     1063
#define DBUILDTEXT                      1064
#define DCOUNT                          1065
#define IDC_HTTP                        1066
#define IDC_SCROLLBAR1                  1067
#define ESFIELD                         1069
#define DPREFFLSORT                     1070
#define IDC_RADIO1                      1072
#define IDC_RADIO2                      1073
#define DSORT_TYPE                      1074
#define IDC_RADIO3                      1074
#define IDC_RB_RECORD                   1074
#define DSORT_AZ                        1075
#define IDC_RADIO4                      1075
#define IDC_RB_GROUPH                   1075
#define DSORT_TABLE                     1076
#define DRIGHTLITERAL                   1079
#define DRBTRUE                         1080
#define DRBFALSE                        1081
#define DLISTMONTH                      1084
#define DLISTDAY                        1085
#define DLISTHOUR                       1086
#define DLISTMONTHEND                   1087
#define DLISTTOMONTH                    1087
#define DLISTDAYEND                     1088
#define DLISTTODAY                      1088
#define DLISTMINUTE                     1089
#define DLISTSECOND                     1090
#define DLISTHOUREND                    1091
#define DLISTTOHOUR                     1091
#define DTEXTCOMPARED                   1092
#define DTEXTVALUE                      1093
#define DTEXTFIELD                      1094
#define DTEXTDATE                       1095
#define DLISTMINUTEEND                  1095
#define DLISTTOMINUTE                   1095
#define DTEXTMONTH                      1096
#define DTEXTDAY                        1097
#define DTEXTYEAR                       1098
#define DTEXTMONTHEND                   1099
#define DTEXTTOMONTH                    1099
#define DLISTVALUES                     1100
#define IDC_FILEPROPERTY_COMMENTS       1101
#define DTEXTDAYEND                     1101
#define DTEXTTODAY                      1101
#define IDC_FILEPROPERTY_AUTHOR         1102
#define DTEXTYEAREND                    1102
#define DTEXTTOYEAR                     1102
#define IDC_FILEPROPERTY_KEYWORDS       1103
#define DSPINYEAR                       1103
#define DTEXTFROMMONTH                  1103
#define IDC_FILEPROPERTY_TITLE          1104
#define DSPINYEAREND                    1104
#define DTEXTFROMDAY                    1104
#define IDC_FILEPROPERTY_SUBJECT        1105
#define DLISTYEAR                       1105
#define IDC_FILEPROPERTY_REPORT         1106
#define DEDITYEAREND                    1106
#define DLISTYEAREND                    1106
#define DLISTTOYEAR                     1106
#define IDC_FILEPROPERTY_SEPARATOR      1107
#define DTEXTHOUR                       1107
#define DTEXTMINUTE                     1108
#define DTEXTSECOND                     1109
#define DTEXTAMPM2                      1110
#define DTEXTHOUREND                    1110
#define DTEXTTOHOUR                     1110
#define DTEXTMINUTEEND                  1111
#define DTEXTTOMINUTE                   1111
#define DTEXTAMPMEND                    1112
#define DTEXTTOSECOND                   1112
#define DLISTAMPMEND                    1113
#define DLISTTOSECOND                   1113
#define DTEXTFROMYEAR                   1114
#define DLISTFROMMONTH                  1115
#define DLISTFROMDAY                    1116
#define DLISTFROMYEAR                   1117
#define DTEXTFROMHOUR                   1118
#define DTEXTFROMMINUTE                 1119
#define IDC_FILESETTINGS_DATA_DIRECTORY 1120
#define DTEXTFROMSECOND                 1120
#define IDC_FILESETTINGS_IMAGE_DIRECTORY 1121
#define DLISTFROMHOUR                   1121
#define IDC_FILESETTINGS_REPORT_DIRECTORY 1122
#define DLISTFROMMINUTE                 1122
#define IDC_FILESETTINGS_INDEX_EXTENSION 1123
#define DLISTFROMSECOND                 1123
#define IDC_FILESETTINGS_TEXT_EXTENSION 1124
#define IDC_FILESETTINGS_IMAGE_EXTENSION 1125
#define IDC_FILESETTINGS_TEMPLATE_DIRECTORY 1126
#define IDC_FILESETTINGS_REPORT_DICTIONARY 1127
#define IDC_FILESETTINGS_DICTIONARY_INDEX 1128
#define IDC_FILESETTINGS_DATA_BROWSE    1129
#define IDC_FILESETTINGS_REPORT_BROWSE  1130
#define IDC_FILESETTINGS_IMAGE_BROWSE   1131
#define IDC_FILESETTINGS_TEMPLATE_BROWSE 1132
#define IDC_FILESETTINGS_REPORT_DICTIONARY_BROWSE 1133
#define IDC_FILESETTINGS_DICTIONARY_INDEX_BROWSE 1134
#define IDC_FILTERPROMPT_PROMPT_STRING  1135
#define IDC_EXPORT_NAME                 1145
#define IDC_EXPORT_NAME_BROWSE          1146
#define IDC_HTMLIMAGE_DIRECTORY         1147
#define IDC_HTMLIMAGE_DIRECTORY_BROWSE  1148
#define IDC_HTMLIMAGE_SAMPLE            1149
#define IDC_HTMLIMAGE_PLACE_SAME        1150
#define IDC_HTMLIMAGE_FILEFORMAT        1151
#define IDC_HTMLIMAGE_COPY_ALL          1152
#define IDC_FIELDPROP_HTML_ANGLE        1153
#define IDC_RICHEDIT                    1155
#define IDC_RICHEDIT1                   1156
#define DTEXTFROM                       1157
#define DTEXTTO                         1158
#define DTEXTOR                         1159
#define IDC_AUTOSAVE                    1160
#define IDC_SPIN1                       1161
#define DPARTLENSPIN                    1161
#define MAX                             1166
#define IDC_QUOTE                       1169
#define IDC_ACTION                      1171
#define IDC_RADIO5                      1174
#define IDC_RB_GROUPF                   1174
#define IDC_RB_RESULT                   1175
#define IDC_RB_COMMA                    1176
#define IDC_RB_TAB                      1178
#define IDC_RB_CHAR                     1179
#define IDC_RB_SDF                      1180
#define IDC_RB_WORKSHEET                1181
#define IDC_RB_EXCEL_CHART              1182
#define IDC_RB_EXCEL_PIVOT              1183
#define IDC_CHECK1                      1184
#define IDC_CHECK_CR                    1184
#define IDC_CHECK_TH                    1184
#define IDC_CHECK_MATCH_CASE            1184
#define IDC_CHECK_PASTE                 1184
#define IDC_CHECK_NOCHANGE              1184
#define IDC_CHECK_CONDITION             1184
#define IDC_CHECK_SHOWDD                1184
#define IDC_CHECK_DEFINE                1184
#define IDC_CHECK_VLIST                 1184
#define IDC_CHECK_BH                    1185
#define IDC_CHECK_WHOLE_WORD            1185
#define IDC_CHECK_REPLACE               1185
#define IDC_COMBO1                      1186
#define IDC_CB_GROUPH                   1186
#define IDC_CB_MESSAGE                  1186
#define IDC_CHECK_LV                    1186
#define IDC_CB_FIND                     1186
#define IDC_CB_HF                       1186
#define IDC_CB_DATATYPE                 1186
#define IDC_FILESETTINGS_LOOKUP_EXTENSION 1186
#define IDC_COMBO2                      1187
#define IDC_CB_GROUPF                   1187
#define IDC_CB_SUBJECT                  1187
#define IDC_CHECK_RV                    1187
#define IDC_CB_REPLACE                  1187
#define IDC_CHECK_PROMPT                1187
#define IDC_EDIT_SUBJECT                1188
#define IDC_CHECK2                      1189
#define IDC_EDIT_MESSAGE                1189
#define IDC_CHECK_NOMARGINS             1189
#define IDC_CHECK3                      1190
#define IDC_CHECK_DOS                   1190
#define IDC_CHECK4                      1191
#define IDC_CHECK_FIELD                 1191
#define IDC_RB_TEXT                     1192
#define IDC_RB_RTF                      1193
#define IDC_RB_HTML                     1194
#define IDC_RB_ACTIVEX                  1195
#define IDC_RB_XBASE                    1196
#define IDC_FILENAME                    1197
#define IDC_RB_TEXT_DATA                1198
#define IDC_CHECK5                      1199
#define IDC_CHECK_QUOTE                 1199
#define IDC_MAPI                        1200
#define IDC_RB_AUTO                     1201
#define IDC_EDIT_SENDTO                 1202
#define IDC_RB_BURST                    1203
#define IDC_CB_BURST                    1204
#define IDC_CB_SENDTO                   1205
#define IDC_RB_SINGLE                   1206
#define IDC_GROUP_MAPI_LEFT             1207
#define IDC_GROUP_MAPI_RIGHT            1208
#define IDC_TEXT_SEND1                  1209
#define IDC_TEXT_BURST                  1210
#define IDC_TEXT_SEND2                  1211
#define IDC_TEXT_SUBJECT                1212
#define IDC_TEXT_MESSAGE                1213
#define IDC_RB_TITLE                    1214
#define IDC_RB_SUMMARY                  1215
#define IDC_GROUP_BAND                  1216
#define IDC_GROUP_TEXT                  1217
#define IDC_TEXT_CHARACTER              1218
#define IDC_LB_GROUPH                   1219
#define IDC_LB_GROUPF                   1220
#define IDC_TEXT_OR1                    1220
#define IDC_TEXT_OR2                    1221
#define IDC_TEXT_RPASS                  1222
#define IDC_TEXT_DPASS                  1223
#define IDC_TEXT_INFO                   1224
#define IDC_RB_NEW_ALLOW_CHOICE         1225
#define IDC_RB_NEW_ALWAYS_USE           1226
#define IDC_CB_DATASOURCE               1227
#define IDC_RB_OPEN_ALLOW_CHOICE        1228
#define IDC_RB_OPEN_ALWAYS_USE          1229
#define IDC_LB_FIELD1                   1230
#define IDC_STATIC_DUPLICATE            1232
#define IDC_LB_L1                       1233
#define IDC_LB_L2                       1234
#define IDC_LB_L3                       1235
#define IDC_LB_FIELDS                   1235
#define IDC_LB_L4                       1236
#define IDC_EB_EXPRESSION               1236
#define IDC_LB_GROUP1                   1239
#define IDC_LB_GROUP2                   1240
#define IDC_PB_REPLACE                  1240
#define IDC_LB_GROUP3                   1241
#define IDC_LCON_FIELDS                 1241
#define IDC_LB_GROUP4                   1242
#define IDC_LCON_LIST                   1242
#define IDC_LB_GROUP5                   1243
#define IDC_LB_GROUP6                   1244
#define IDC_RBX0                        1244
#define IDC_LB_GROUP7                   1245
#define IDC_LCON_FROM                   1245
#define IDC_LB_GROUP8                   1246
#define IDC_LCON_FROM2                  1246
#define IDC_RBX1                        1246
#define IDC_LCON_TO                     1246
#define IDC_PB_MULTI_EDIT               1247
#define IDC_RBX2                        1247
#define IDC_LIST1                       1248
#define IDC_RBX3                        1248
#define IDC_PB_FUNCTION                 1249
#define IDC_EB_XNAME                    1250
#define IDC_TEXT_NAME                   1251
#define IDC_TEXT_EXPRESSION             1252
#define IDC_LCON_FUNCTIONS              1253
#define IDC_PB_VERIFY                   1254
#define IDC_LB_RESET                    1255
#define IDC_LB_ACCUM                    1256
#define IDC_LB_SELECTED                 1257
#define IDC_FIELD                       1259
#define IDC_LB_FIELD                    1260
#define IDC_EB_NUMBER                   1261
#define IDC_SPIN_NUMBER                 1263
#define IDC_EB_HEIGHT                   1264
#define IDC_SPIN                        1265
#define IDC_PB_CLEAR                    1266
#define IDC_PB_SELECT_LINK              1267
#define IDC_EB_NAME                     1268
#define IDC_PB_ADD                      1269
#define IDC_PB_EDIT                     1270
#define IDC_TEXT_DEFAULT                1271
#define IDC_EB_INSTRUCTIONS             1272
#define IDC_PB_EDIT2                    1272
#define IDC_EB_CAPTION                  1273
#define IDC_EB_ERROR                    1274
#define IDC_EB_FORMAT                   1275
#define IDC_TEXT_VALUE                  1277
#define IDC_TEXT_VALUE2                 1278
#define IDC_GROUP_EDIT                  1279
#define IDC_PB_MODIFY                   1280
#define IDC_TEXT_INSTR                  1281
#define IDC_LB_RIGHTFIELD               1282
#define IDC_MCFRAME                     1282
#define IDC_BUTTON2                     1283
#define IDC_DT_TIME                     1283
#define IDC_PB_DATE_VALID               1283
#define IDC_RIGHTFIELD                  1284
#define IDC_BUTTON3                     1284
#define IDC_PB_TIME_VALID               1284
#define IDC_PB_LOOKUP                   1284
#define IDC_MONTHCALENDAR1              1285
#define IDC_DTFRAME                     1286
#define IDC_DT_TIME_VALID               1286
#define IDC_DATETIMEPICKER1             1287
#define IDC_DATETIMEPICKER2             1288
#define IDC_DATETIMEPICKER3             1289
#define IDC_PB_TO_TABLE                 1289
#define IDC_DATETIMEPICKER4             1290
#define IDC_EB_TO_TABLE                 1290
#define IDC_DATETIMEPICKER5             1291
#define IDC_EB_TO_ALIAS                 1291
#define IDC_DATETIMEPICKER6             1292
#define IDC_LB_FROM                     1292
#define IDC_BUTTON_DATE                 1293
#define IDC_DATETIMEPICKER7             1294
#define IDC_EB_FROM_TABLE               1294
#define IDC_DATETIMEPICKER8             1295
#define IDC_EB_FROM_ALIAS               1295
#define IDC_BUTTON4                     1296
#define IDC_LB_TO                       1296
#define IDC_TABLE                       1296
#define IDC_PB_TABLE                    1296
#define IDC_BUTTON_DATE_FROM            1297
#define IDC_PB_DELETE1                  1297
#define IDC_EDIT_DATE_FROM              1298
#define IDC_TEXT_PREPROCESS             1298
#define IDC_BUTTON_DATE_TO              1299
#define IDC_EDIT_DATE_TO                1300
#define IDC_BUTTON5                     1300
#define IDC_VALUE_FIELD                 1300
#define IDC_PB_VALUE_FIELD              1300
#define IDC_EDIT_DATE                   1301
#define IDC_BUTTON6                     1301
#define IDC_CLEAR_TABLE                 1301
#define IDC_PB_CLEAR_TABLE              1301
#define IDC_DYNAMIC_LIST                1302
#define IDC_CAL1                        1302
#define IDC_STATIC_LIST                 1303
#define IDC_CAL2                        1303
#define IDC_VALUE_LIST                  1304
#define IDC_CAL3                        1304
#define IDC_VALID_TABLE                 1305
#define IDC_CAL4                        1305
#define IDC_TEXT_TABLE                  1306
#define IDC_CAL5                        1306
#define IDC_CAL6                        1307
#define IDC_PB_CLEAR_FIELD              1308
#define IDC_STATIC_DYN                  1309
#define IDC_STATIC_TABLE                1310
#define IDMASTEROPENDICT                1312
#define ID_RELATION                     1318
#define DPREDEFIND                      1319
#define DPREDEFIND01                    1319
#define DUSERINDEX01                    1320
#define DRECNO01                        1321
#define DRALIAS01                       1322
#define IDC_STATIC_LINKFIELD            1323
#define IDC_STATIC_RELATE_TABLE         1324
#define IDC_STATIC_RELATE_INDEX         1325
#define IDC_STATIC_RELATE_TYPE          1326
#define IDC_STATIC_CHAR_MATCH           1327
#define IDC_STATIC_FAILURE_ACTION       1328
#define IDI_RRAPP                       10000
#define IDR_SRVR_INPLACE                10001
#define IDS_MULTIPLE_FIELDS             10001
#define IDR_SRVR_EMBEDDED               10002
#define IDR_CNTR_INPLACE                10003
#define IDD_ABOUTBOX                    10004
#define IDP_OLE_INIT_FAILED             10005
#define IDP_FAILED_TO_CREATE            10006
#define IDB_PREVBAR                     10008
#define IDW_PREVBAR                     10009
#define IDC_CURSOR1                     10011
#define IDR_PREVACC                     10012
#define IDD_PREPRINT                    10013
#define IDW_SPLITVIEW                   10014
#define IDD_PREVPGDLG                   10015
#define IDD_PSTATDLG                    10016
#define IDD_TRIM                        10017
#define IDD_ALIGN                       10018
#define IDD_CHARWIDTH                   10019
#define IDM_FLD_COMMENT                 10020
#define IDR_FLD_PROPERTIES              10021
#define IDR_LINE_PROPERTIES             10022
#define IDD_DATEPIC                     10023
#define IDD_NUMPIC                      10024
#define IDB_FORMBAR                     10025
#define IDW_EDIT_TEXT                   10026
#define IDD_DATETIMEPIC                 10027
#define IDD_TIMEPIC                     10028
#define IDR_MAINFRAME                   10029
#define IDI_FNWIZ                       10030
#define IDI_FNWIZD                      10031
#define IDI_FNWIZF                      10032
#define IDI_FNTEMP                      10033
#define IDI_FNTEMPD                     10034
#define IDI_FNTEMPF                     10035
#define IDI_FNINST                      10036
#define IDI_FNINSTD                     10037
#define IDI_FNINSTF                     10038
#define IDI_FNBLANK                     10039
#define IDI_FNBLANKD                    10040
#define IDI_FNBLANKF                    10041
#define IDI_FNOPEN                      10042
#define IDI_FNOPEND                     10043
#define IDI_FNOPENF                     10044
#define IDD_TEXTPROPDLG                 10045
#define IDD_FLDCOMMENT                  10046
#define IDD_INSFLD                      10047
#define IDD_RULERS                      10048
#define IDW_RULER                       10049
#define IDD_HTML2_EXPORT                10050
#define IDD_CREATE_HTML                 10051
#define IDD_PDI_EXPORT                  10052
#define IDD_HTML2_PAGE_BACKGROUND       10053
#define IDD_HTML2_PAGE_BORDER           10054
#define IDD_HTML2_PAGE_LOCATION         10055
#define IDD_FIELDPROP_PAGE_EXPORT       10056
#define IDD_ACTX_VIEW_HTML_DLG          10057
#define IDD_FILTER_PROMPT               10058
#define IDD_VALUELISTS                  10059
#define IDB_BITMAP1                     10063
#define IDB_BITMAP2                     10064
#define IDB_BITMAP3                     10065
#define IDB_BITMAP4                     10066
#define IDB_BITMAP5                     10067
#define IDB_BITMAP6                     10068
#define IDB_BITMAP7                     10069
#define IDB_BITMAP8                     10070
#define IDB_BITMAP9                     10071
#define IDB_BITMAP10                    10072
#define IDC_CURSOR2                     10073
#define IDD_MAPI_OPTIONS                10074
#define IDD_DIALOG1                     10077
#define IDB_RUNPREVBAR                  10078
#define IDB_MAINFRAME                   10081
#define IDB_BITMAP11                    10083
#define IDD_RULERSX                     10085
#define IDD_PASSWORD                    10086
#define IDD_PREFS_DATASOURCE            10087
#define IDD_DUPLICATE_DBF               10088
#define XIDD_INSERT_FIELD               10089
#define IDD_INSERT_FIELD                10090
#define IDD_CALC_FIELDS                 10091
#define IDD_TOTAL_FIELDS                10092
#define IDD_UDFS                        10093
#define IDD_PARAM_FIELDS                10094
#define IDD_PARAMS_LIST                 10094
#define IDD_UDF_INSERT                  10095
#define IDD_CALC_INSERT                 10096
#define IDD_CALC_EDIT                   10097
#define IDD_XEDIT                       10097
#define IDD_GROUP                       10098
#define IDD_SELECT_GROUP_FIELD          10099
#define IDD_SORT                        10100
#define IDC_CURSOR3                     10101
#define IDD_REPLACE                     10102
#define IDD_UNDO_LIST                   10103
#define IDD_BAND_PROPERTIES             10104
#define IDD_TOTAL_MULTI_EDIT_TYPE       10105
#define IDD_MTOTAL_TYPE                 10105
#define IDD_TOTAL_MULTI_EDIT_SELECT     10106
#define IDD_MTOTAL_SELECT               10106
#define IDD_SELECT_FUNCTION             10107
#define IDD_TOTAL_MULTI_EDIT_TARGET     10108
#define IDD_MTOTAL_TARGET               10108
#define IDD_TOTAL_MULTI_EDIT_RESET      10109
#define IDD_MTOTAL_RESET                10109
#define IDD_TOTAL_MULTI_EDIT_ACCUM      10110
#define IDD_MTOTAL_ACCUM                10110
#define IDD_TOTAL_MULTI_EDIT_PROCESS    10111
#define IDD_MTOTAL_PROCESS              10111
#define IDD_TOTAL_MULTI_EDIT_OK         10112
#define IDD_MTOTAL_OK                   10112
#define IDI_ICON_GO                     10113
#define IDI_ICON_NOGO                   10114
#define IDI_ICON_MAYBE                  10115
#define IDD_TOTAL_NAME                  10116
#define IDI_ICON_GO1                    10116
#define IDI_ICON_BLANK                  10116
#define IDD_TOTAL_TYPE                  10117
#define IDD_TOTAL_TARGET                10118
#define IDD_TOTAL_RESET                 10119
#define IDD_TOTAL_ACCUM                 10120
#define IDD_TOTAL_PROCESS               10121
#define IDD_TOTAL_CONDITION             10122
#define IDD_TOTALS_RESET_ALL            10126
#define IDD_DIALOG2                     10127
#define IDD_MTOTAL_CONDITION            10128
#define IDD_CREATE_BAND                 10129
#define IDD_PASTE_BAND                  10132
#define IDD_BAND_TYPE                   10133
#define IDD_BAND_HEIGHT                 10134
#define IDD_BAND_CONDITION              10135
#define IDD_INSERT_DB_FIELD             10136
#define IDD_PARAMS_NAME                 10137
#define IDD_PARAMS_ENTER                10138
#define IDI_ICON_CHECK                  10139
#define IDI_ICON_UNCHECK                10140
#define IDB_CLOCK                       10140
#define IDB_CALENDAR                    10141
#define IDD_SELECT_TO_FIELD             10142
#define IDD_JOIN                        10143
#define IDD_JOIN_FUTURE                 10143
#define IDD_JOIN1                       10144
#define DRELATE01                       10147
#define DRELATE02                       10148
#define DRELATE03                       10149
#define DRELATE04                       10150
#define DRELATE05                       10151
#define DRELATE06                       10152
#define IDD_DIALOG3                     10153
#define IDB_BITMAP_CHARMATCHFULL1       11111
#define IDB_BITMAP_RELATEDTABLETAB      11112
#define IDB_BITMAP_EXACT                11113
#define IDB_BITMAP_TYPETABSCAN          11114
#define IDB_BITMAP_TYPETABAPPROX        11115
#define IDB_BITMAP_CHARMATCHPARTIAL1    11116
#define IDB_BITMAP_BLANKFAILURE         11117
#define IDB_BITMAP_SKIPFAILURE          11118
#define IDD_ACTX_INPUT_FILE_DLG         24464
#define IDD_ACTX_OBJ_TAG_DLG            25464
#define IDC_BUTTON_VIEW_HTML            25465
#define IDD_CHARPIC                     25465
#define IDD_PREFS_DISPLAY               25465
#define IDD_PREFS_FILENEW               25466
#define IDD_PREFS_MEMOEDIT              25467
#define IDD_PREFS_FIELDLISTS            25468
#define IDD_PREFS_AUTOSAVE              25469
#define IDD_EXPORT_TYPE                 25470
#define IDD_EXPORT_MAPI                 25471
#define IDD_EXPORT_OPTIONS              25472
#define IDD_EXPORT_OPTIONS_TEXT_XBASE   25474
#define IDD_EXPORT_OPTIONS_HTML         25475
#define IDD_EXPORT_OPTIONS_ACTIVEX      25476
#define IDD_EXPORT_OPTIONS_EXCEL_CHART  25477
#define IDD_PARAMS_VALUE                25477
#define IDD_PARAMS_PRESENT              25478
#define IDD_PARAMS_VALIDATE             25479
#define IDD_PARAMS_VALIDATE_LIST        25480
#define IDC_EDIT_HTML_CODE              26465
#define ID_CANCEL_EDIT                  32768
#define IDM_EDITTEXT                    32771
#define ID_OLE_SAVE_AS_PICTURE          32774
#define ID_BUTTON32774                  32774
#define ID_BUTTON32775                  32775
#define ID_BUTTON32776                  32776
#define ID_BUTTON32777                  32777
#define ID_BUTTON32778                  32778
#define ID_BUTTON32779                  32779
#define ID_BUTTON32780                  32780
#define ID_BUTTON32781                  32781
#define ID_BUTTON32782                  32782
#define ID_BUTTON32783                  32783
#define ID_BUTTON32784                  32784
#define ID_BUTTON32785                  32785
#define ID_BUTTON32786                  32786
#define IDM_EXPORT_RESULTSET            32787
#define ID_BUTTON32788                  32788
#define ID_BUTTON32789                  32789
#define ID_BUTTON32790                  32790
#define ID_BUTTON32791                  32791
#define ID_BUTTON32792                  32792
#define ID_BUTTON32793                  32793
#define ID_BUTTON32794                  32794
#define ID_BUTTON32795                  32795
#define ID_BUTTON32796                  32796
#define ID_BUTTON32797                  32797
#define ID_BUTTON32798                  32798
#define ID_BUTTON32799                  32799
#define ID_BUTTON32800                  32800
#define ID_BUTTON32801                  32801
#define ID_BUTTON32802                  32802
#define ID_BUTTON32803                  32803
#define ID_BUTTON32804                  32804
#define ID_BUTTON32805                  32805
#define ID_BUTTON32806                  32806
#define IDM_PARAMS                      32808
#define ID_BUTTON32809                  32809
#define ID_BUTTON32810                  32810
#define IDM_INSIMAGEFIELD               32812
#define ID_RRUndo                       32814
#define ID_BUTTON32817                  32817
#define ID_FORMAT_ALIGN                 32818
#define ID_FORMAT_ALIGN_LEFT            32819
#define ID_FORMAT_ALIGN_CENTER          32820
#define ID_FORMAT_ALIGN_RIGHT           32821
#define ID_FORMAT_ALIGN_TOP             32822
#define ID_FORMAT_ALIGN_MIDDLE          32823
#define ID_FORMAT_ALIGN_BOTTOM          32824
#define ID_BUTTON32825                  32825
#define ID_UNDOLIST                     32826
#define ID_FILE_EXPORTOLE_EXCELCHART    32827
#define ID_FILE_EXPORTOLE_EXCELPIVOTTABLE 32828
#define IDM_VIEWRULER                   32829
#define IDM_SECURITY                    32830
#define ID_BUTTON32831                  32831
#define ID_VIEW_TOPHORZRULER            32850
#define ID_VIEW_BOTTOMHORZRULER         32851
#define ID_VIEW_LEFTVERTRULER           32852
#define ID_VIEW_RIGHTVERTRULER          32853
#define ID_INDICATOR_LINEINCH           59142
#define IDW_FORMBAR                     0xE804
#define IDS_TEMP_DBF_EXPORTFILE         61205
#define IDS_RESULTSET                   61206
#define IDS_SELECTBURSTFIELD            61207

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        10154
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1330
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
