//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by F:\RR\RESOURCE\chart.rc
//
#define IDC_EDIT_CHART_WIDTH            206
#define IDC_SPIN_CHART_WIDTH            207
#define IDC_EDIT_CHART_HEIGHT           208
#define IDC_SPIN_CHART_HEIGHT           209
#define IDC_GROUP_SIZE                  212
#define IDR_CHARTTTYPE                  929
#define IDB_BAR_BYHAND                  931
#define IDD_BAR_CHART                   932
#define IDD_PIE_CHART                   933
#define IDD_LINE_CHART                  934
#define IDB_BAR2D_GSW_U                 934
#define IDB_PIE2D_GSW_U                 935
#define IDD_AREA_CHART                  935
#define IDD_SCATTER_CHART               936
#define IDB_BAR2D_GSW_D                 936
#define IDD_TYPE_CHART                  937
#define IDB_NYI_U                       937
#define IDD_TEXT_CHART                  938
#define IDD_DATA_CHART                  939
#define IDB_BAR2D_GSW_F                 939
#define IDD_OPTIONS_CHART               940
#define IDD_OHLC_CHART                  941
#define IDB_AREA_GSW_U                  941
#define IDD_BUBBLE_CHART                942
#define IDB_BUBBLE_GSW_U                942
#define IDB_LINE_GSW_U                  943
#define IDB_SCAT_GSW_U                  944
#define IDB_OHLC_GSW_U                  945
#define IDB_AREA_GSW_F                  951
#define IDB_PIE2D_GSW_F                 952
#define IDD_FONT_CHART                  953
#define IDD_OHLC_DATA_CHART             954
#define IDD_SCATTER_DATA_CHART          955
#define IDD_BUBBLE_DATA_CHART           956
#define IDC_BAR_STACKED                 1000
#define IDC_BAR_SIMPLE                  1001
#define IDC_HORIZONTAL                  1005
#define IDC_VERTICAL                    1006
#define IDC_BAR_STACKED_PERCENT         1007
#define IDC_BAR_STACKED_FLOATING        1008
#define IDC_LINE_ABSOLUTE               1009
#define IDC_STICKS                      1010
#define IDC_LINES                       1011
#define IDC_FIT_TO_CURVE                1012
#define IDC_TYPE_2D                     1013
#define IDC_TYPE_3D                     1014
#define IDC_BAR                         1024
#define IDC_PIE                         1025
#define IDC_TYPE_HLC                    1025
#define IDC_LINE                        1026
#define IDC_AREA                        1027
#define IDC_TYPE_OHLC_CSTICK            1027
#define IDC_SCATTER                     1028
#define IDC_TYPE_HL                     1028
#define IDC_OHLC                        1029
#define IDC_BUBBLE                      1030
#define IDC_TICK_OC                     1030
#define IDC_FILLER                      1031
#define IDC_TICK_HL                     1031
#define IDC_TYPE_OHLC                   1032
#define IDC_LINE_STACKED                1036
#define IDC_LINE_STACKED_PERCENT        1037
#define IDC_GROUP_ORIENTATION           1038
#define IDC_LEGEND_YES                  1039
#define IDC_LEGEND_NO                   1040
#define IDC_STATIC_TITLE                1041
#define IDC_EDIT_TITLE                  1042
#define IDC_STATIC_CATEGORY             1043
#define IDC_STATIC_VALUE                1044
#define IDC_EDIT_CATEGORY               1045
#define IDC_EDIT_VALUE                  1046
#define IDC_CHART_PICTURE               1047
#define IDC_GROUP_ANCHOR                1048
#define IDC_STATIC_DEPTH                1048
#define IDC_ANCHOR_TOP                  1049
#define IDC_EDIT_DEPTH                  1049
#define IDC_ANCHOR_BOTTOM               1050
#define IDC_DATA_LABEL                  1051
#define IDC_DATA_COLLECT                1051
#define IDC_LIST2                       1052
#define IDC_DATA_FIELDS                 1052
#define IDC_STATIC_LABEL                1053
#define IDC_STATIC_DATA                 1054
#define IDC_HORIZONTAL_LINE             1058
#define IDC_VERTICAL_LINE               1059
#define IDC_AREA_ABSOLUTE               1060
#define IDC_AREA_STACKED                1061
#define IDC_AREA_STACKED_PERCENT        1062
#define IDC_COMBO_LABEL                 1065
#define IDC_BTN_COLLECT_UP              1066
#define IDC_STATIC_SORT                 1067
#define IDC_STATIC_COLLECT              1068
#define IDC_COMBO_SORT                  1069
#define IDC_GROUP_SUBCATEGORY           1070
#define IDC_CHECK_SORT_ASCENDING        1071
#define IDC_STATIC_SUBCAT_FIELD         1072
#define IDC_COMBO_SUBCAT_FIELD          1073
#define IDC_STATIC_SUBCAT_LABEL         1074
#define IDC_COMBO_BUBBLE_Y              1074
#define IDC_COMBO_OHLC_HIGH             1074
#define IDC_COMBO_SUBCAT_LABEL          1075
#define IDC_COMBO_BUBBLE_DIAMETER       1075
#define IDC_COMBO_OHLC_LOW              1075
#define IDC_STATIC_SUBCAT_SORT          1076
#define IDC_COMBO_OHLC_CLOSE            1076
#define IDC_COMBO_SUBCAT_SORT           1077
#define IDC_COMBO_OHLC_LABEL            1077
#define IDC_CHECK_SUBCAT_ASCENDING      1078
#define IDC_BTN_ADD_COLLECT             1079
#define IDC_BTN_REMOVE_COLLECT          1080
#define IDC_BTN_COLLECT_DN              1081
#define IDC_GROUP_CHART_TYPE            1081
#define IDC_CHECK_SUBCAT_COMBINE        1084
#define IDC_CHECK_SORT_COMBINE          1085
#define IDC_STATIC_GROUP_SORT           1086
#define IDC_CHECK_LEGEND                1087
#define IDC_BTN_SUBCAT_CLEAR            1088
#define IDC_CHECK_DATA_LABEL            1089
#define IDC_BTN_HORIZONTAL_Y            1090
#define IDC_BTN_TOPTOBOT_Y              1091
#define IDC_GROUP_RANGE                 1092
#define IDC_BTN_AUTO                    1093
#define IDC_BTN_NORMALIZE               1094
#define IDC_BTN_DEFINED                 1095
#define IDC_EDIT_RANGE_MIN              1096
#define IDC_STATIC_MIN                  1097
#define IDC_STATIC_MAX                  1098
#define IDC_EDIT_RANGE_MAX              1099
#define IDC_CHART_FONT_BASE             1100
#define IDC_CHART_FONT_BASE_BROWSE      1101
#define IDC_CHART_FONT_PALETTE_LIST     1102
#define IDC_COMBO_BUBBLE_X              1104
#define IDC_COMBO_OHLC_OPEN             1104
#define IDC_COMBO_SCATTER_X             1105
#define IDC_COMBO_SCATTER_Y             1106
#define IDC_BTN_BOTTOTOP_Y              1107
#define IDC_PIE_NOLABEL                 1108
#define IDC_PIE_CONNECTLINES            1109
#define IDC_GROUP_PIE_STYLE             1110
#define IDC_PIE_COLORSLICE              1111
#define IDC_PIE_PERCENT                 1112
#define IDC_TITLE_FONT                  1113
#define IDC_AXIS_TITLE_FONT             1114
#define IDC_DATA_LABEL_FONT             1115
#define IDC_LEGEND_FONT                 1116
#define IDC_FONT_SIZE_SMALLEST          1117
#define IDC_FONT_SIZE_SMALLER           1118
#define IDC_FONT_SIZE_SMALL             1119
#define IDC_FONT_SIZE_NORMAL            1120
#define IDC_FONT_SIZE_LARGE             1121
#define IDC_FONT_SIZE_LARGER            1122
#define IDC_FONT_SIZE_LARGEST           1123
#define IDC_GROUP_FONT                  1124
#define IDC_CHART_FONT_SIZE             1125
#define IDC_STATIC_FONT_NAME            1126
#define IDC_STATIC_FONT_SIZE            1127
#define IDC_LB_VALUE                    1127
#define IDC_LB_LABEL                    1128
#define IDC_LB_SORT                     1129
#define IDC_VALUE                       1130
#define IDC_LABEL                       1131
#define IDC_SORT                        1132
#define IDC_LB_FIELD_SORT               1133
#define IDC_FIELD_SORT                  1134
#define IDC_LIST3                       1136
#define IDC_LB_LABEL_FIELD              1136
#define IDC_FIELD_LABEL                 1137
#define IDC_LABEL_FIELD                 1137
#define IDS_FONT_PALETTE_0              8010
#define IDS_FONT_PALETTE_1              8011
#define IDS_FONT_PALETTE_2              8012
#define IDS_FONT_PALETTE_3              8013
#define IDS_FONT_PALETTE_4              8014
#define IDS_FONT_PALETTE_5              8015
#define IDS_FONT_PALETTE_6              8016
#define IDS_FONT_PALETTE_7              8017
#define IDS_FONT_PALETTE_8              8018
#define IDS_FONT_PALETTE_9              8019
#define IDS_FONT_PALETTE_10             8020
#define IDI_ARROW_DN                    11001
#define IDI_ARROW_UP                    11002
#define ID_CHART_INSERT                 32771
#define IDC_STATIC_WIDTH                65535
#define IDC_STATIC_HEIGHT               65535
#define IDC_GROUP_STYLE                 65535
#define IDC_GROUP_TITLES                65535
#define IDC_GROUP_DIMENSION             65535
#define IDC_GROUP_GRID_LINES            65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        958
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1138
#define _APS_NEXT_SYMED_VALUE           1001
#endif
#endif
